src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use phpDocumentor\Reflection\Types\Boolean;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\GreaterThan('yesterday')]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $start_date = null;

    #[Assert\GreaterThan('yesterday')]
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTime $end_date = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 20, scale: 2, nullable: true)]
    private ?string $total_price = null;

    #[ORM\Column(type: Types::BOOLEAN, options: ['default' => false])]
    private ?bool $isPaid = false;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    private ?User $customer = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    private ?Room $room = null;

    /**
     * @var Collection<int, Review>
     */
    #[ORM\OneToMany(targetEntity: Review::class, mappedBy: 'booking', orphanRemoval: true)]
    private Collection $review;



    public function __construct()
    {
        $this->review = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStartDate(): ?\DateTime
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTime $start_date): static
    {
        $this->start_date = $start_date;
        return $this;
    }

    public function getEndDate(): ?\DateTime
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTime $end_date): static
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getTotalPrice(): ?string
    {
        return $this->total_price;
    }

    public function setTotalPrice(string $total_price): static
    {
        $this->total_price = $total_price;

        return $this;
    }

    public function getIsPaid(): ?bool
    {
        return $this->isPaid;
    }

    public function setIsPaid(bool $isPaid): static
    {
        $this->isPaid = $isPaid;

        return $this;
    }


    public function getCustomer(): ?User
    {
        return $this->customer;
    }

    public function setCustomer(?User $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): static
    {
        $this->room = $room;

        return $this;
    }

    /**
     * @return Collection<int, Review>
     */
    public function getReview(): Collection
    {
        return $this->review;
    }

    public function addReview(Review $review): static
    {
        if (!$this->review->contains($review)) {
            $this->review->add($review);
            $review->setBooking($this);
        }

        return $this;
    }

    public function removeReview(Review $review): static
    {
        if ($this->review->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getBooking() === $this) {
                $review->setBooking(null);
            }
        }

        return $this;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Entity\Room;
use DateTime;
use Symfony\Component\Form\Extension\Core\Type\ButtonType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\MakerBundle\Str;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\GreaterThan;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('start_date', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'value' => (new DateTime())->format('Y-m-d'),
                ]
            ])
            ->add('end_date', DateType::class, [
                'widget' => 'single_text',

            ])
            ->add('room', EntityType::class, [
                'class' => Room::class,
                'choice_label' => 'id',
            ])
            ->add('total_price', HiddenType::class, [
                'mapped' => false,
                'attr' => ['type' => 'hidden'],
                'required' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use App\Repository\RoomRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use App\Entity\Room;
use Exception;
use Psr\Log\LoggerInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

#[IsGranted('ROLE_USER')]
#[Route('/booking')]

final class BookingController extends AbstractController
{
    #[Route(name: 'app_booking_index', methods: ['GET'])]
    public function index(BookingRepository $bookingRepository, EntityManagerInterface $em, Request $request): Response
    {
        $page = $request->query->getInt('page', 1);

        $bookings = $em->createQueryBuilder()
            ->select('bookings')
            ->from(Booking::class, 'bookings')
            ->where('bookings.customer = :customer')
            ->setParameter('customer', $this->getUser())
            ->setFirstResult($page * 10 - 10)
            ->setMaxResults(10)
            ->getQuery()
            ->getResult();

        return $this->render('booking/index.html.twig', [
            'bookings' => $bookings,
            'page' => $page
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route(path: '/all', name: 'app_booking_index_all', methods: ['POST', 'GET'])]
    public function index_all(Request $request, BookingRepository $bookingRepository): Response
    {
        $page = $request->query->getInt('page', 1);

        $totalBookings = count($bookingRepository->findAll());
        $lastPage = (int) ceil($totalBookings / 5);



        $bookings = $bookingRepository->createQueryBuilder('b')
            ->setFirstResult($page * 5 - 5)
            ->setMaxResults(5)
            ->getQuery()
            ->getResult();

        return $this->render('booking/index_all.html.twig', [
            'bookings' => $bookings,
            'page' => $page,
            'lastPage' => $lastPage,
        ]);
    }


    #[IsGranted('ROLE_USER')]
    #[Route('/new', name: 'app_booking_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, LoggerInterface $logger, RoomRepository $roomRepository, SessionInterface $session): Response
    {
        $booking = new Booking();

        if ($chosen_room = $request->request->get('chosen_room')) {
            $session->set('chosen_room', $chosen_room);
        }
        $chosen_room = $session->get('chosen_room', null);

        $price = 0;
        if ($chosen_room) {
            $chosen_room_object = $roomRepository->find($chosen_room);
            $price = $chosen_room_object->getPrice();
        }

        if ($chosen_room) {
            $booking->setRoom($entityManager->getRepository(Room::class)->find($chosen_room));
        }

        $booking->setCustomer($this->getUser());
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $start = $booking->getStartDate();
            $end = $booking->getEndDate();
            $room = $booking->getRoom();
            $backendTotal = null;

            if ($start && $end && $room) {
                $interval = $start->diff($end);
                $days = $interval->days;
                $pricePerDay = method_exists($room, 'getPrice') ? (float) $room->getPrice() : 0;
                $backendTotal = number_format($days * $pricePerDay, 2, '.', '');
                $booking->setTotalPrice($backendTotal);
            }

            $frontendTotal = $form->get('total_price')->getData();

            if ($frontendTotal !== $backendTotal) {
                $this->addFlash('warning', 'Price mismatch. Please try again.');

                return $this->render('booking/new.html.twig', [
                    'booking' => $booking,
                    'form' => $form,
                    'chosen_room' => $chosen_room,
                    'price' => $price
                ], new Response('', 422));
            }

            $entityManager->persist($booking);
            $entityManager->flush();

            $this->addFlash('success', 'Booking was created');
            $logger->info('custom log: new booking created:' . $booking->getId() . ' by user: ' . $booking->getCustomer()->getName());

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('booking/new.html.twig', [
            'booking' => $booking,
            'form' => $form,
            'chosen_room' => $chosen_room,
            'price' => $price
        ]);
    }


    #[IsGranted('ROLE_USER')]
    #[Route('/{id}', name: 'app_booking_show', methods: ['GET'])]
    public function show(Booking $booking): Response
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}/edit', name: 'app_booking_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Booking $booking, EntityManagerInterface $entityManager, LoggerInterface $logger): Response
    {

        $isPaid = $request->request->get('isPaid', $booking->getIsPaid());


        dump($booking->getIsPaid());
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        $entityManager->persist($booking->setIsPaid($isPaid));
        $entityManager->flush();

        $logger->info('custom log: booking ' . $booking->getId() . ' was edited by admin');
        $this->addFlash('success', 'Booking was edited');

        return $this->render('booking/edit.html.twig', [
            'booking' => $booking,
            'form' => $form,
            'isPaid' => $isPaid,
        ]);
    }
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/{id}', name: 'app_booking_delete', methods: ['POST'])]
    public function delete(Request $request, Booking $booking, EntityManagerInterface $entityManager, LoggerInterface $logger): Response
    {
        if ($this->isCsrfTokenValid('delete' . $booking->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($booking);
            $entityManager->flush();
        }

        $logger->info('custom log: booking ' . $booking->getId() . ' was deleted by admin');
        $this->addFlash('success', 'Booking was deleted');

        return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
    }

}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('app_booking_delete', { id: booking.id }) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
  <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}" />
  <button class="btn btn-danger">Delete</button>
</form>

templates/booking/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
<button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/booking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Edit Booking
{% endblock %}

{% block body %}
  <h1>Edit Booking</h1>

  {{ include('booking/_form.html.twig', { button_label: 'Update' }) }}
  {% if 'ROLE_ADMIN' in app.user.roles %}
    {{ booking.isPaid ? 'This booking is paid' : 'This booking is not paid' }}

    <form action="edit" method="post" data-turbo="false">
      <input type="hidden" name="isPaid" value="{{ booking.isPaid ? 0 : 1 }}" />
      <button type="submit">Change Payment Status</button>
    </form>

    <a href="{{ path('app_booking_index_all') }}" class="btn btn-primary">back to list</a>
  {% else %}
    <a href="{{ path('app_booking_index') }}" class="btn btn-primary">back to list</a>
  {% endif %}

  {{ include('booking/_delete_form.html.twig') }}
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Booking index
{% endblock %}

{% block body %}
  {% block header %}
    {{ parent() }}
  {% endblock %}

  <div class="example-wrapper">
    <a href="{{ path('app_room') }}"><h4>All rooms</h4></a>
    <h4>My bookings</h4>

    <table class="table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Start_date</th>
          <th>End_date</th>
          <th>Total_price</th>
          <th>Is paid</th>
          <th>Actions</th>
          <th>Booking reviews</th>
        </tr>
      </thead>
      <tbody>
        {% for booking in bookings %}
          <tr>
            <td>{{ booking.id }}</td>
            <td>{{ booking.startDate ? booking.startDate|date('Y-m-d') : '' }}</td>
            <td>{{ booking.endDate ? booking.endDate|date('Y-m-d') : '' }}</td>
            <td>{{ booking.totalPrice }}</td>
            <td>{{ booking.isPaid ? 'paid' : 'not paid' }}</td>
            <td>
              <a href="{{ path('app_booking_show', { id: booking.id }) }}" class="btn btn-primary">show</a>
              <a href="{{ path('app_booking_edit', { id: booking.id }) }}" class="btn btn-primary">edit</a>
            </td>
            <td>
              <a href="{{ path('app_review_index', { bookingId: booking.id }) }}" class="btn btn-primary">My booking reviews</a>
            </td>
          </tr>
        {% else %}
          <tr>
            <td colspan="5">no records found</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {# <a href="{{ path('app_booking_new') }}">Create new</a> #}
    {% if page > 1 %}
      <a href="{{ path('app_booking_index', { page: page - 1 }) }}">Prev</a>
    {% endif %}
    <a href="{{ path('app_booking_index', { page: page + 1 }) }}">Next</a>
  </div>
  {# wrapper end #}
{% endblock %}

templates/booking/index_all.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Booking index
{% endblock %}

{% block body %}
  {% block header %}
    {{ parent() }}
  {% endblock %}
  <h1>All bookings (seen by admin)</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Id</th>
        <th>Start_date</th>
        <th>End_date</th>
        <th>Total_price</th>
        <th>Is paid</th>
        <th>user</th>
        <th>actions</th>
      </tr>
    </thead>
    <tbody>
      {% for booking in bookings %}
        <tr>
          <td>{{ booking.id }}</td>
          <td>{{ booking.startDate ? booking.startDate|date('Y-m-d') : '' }}</td>
          <td>{{ booking.endDate ? booking.endDate|date('Y-m-d') : '' }}</td>
          <td>{{ booking.totalPrice }}</td>
          <td>{{ booking.isPaid ? 'paid' : 'not paid' }}</td>
          <td>{{ booking.customer.email }}</td>
          <td>
            <a href="{{ path('app_booking_show', { id: booking.id }) }}" class="btn btn-primary">show</a>
            <a href="{{ path('app_booking_edit', { id: booking.id }) }}" class="btn btn-primary">edit</a>
          </td>
        </tr>
      {% else %}
        <tr>
          <td colspan="5">no records found</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{{ path('app_booking_new') }}">Create new</a>

  <a href="{{ path('app_booking_index_all', { page: 1 }) }}">1</a>
  <a href="{{ path('app_booking_index_all', { page: 2 }) }}">2</a>
  {% if page > 1 %}
    <a href="{{ path('app_booking_index_all', { page: page - 1 }) }}">Prev</a>
  {% endif %}

  {% if page < lastPage %}
    <a href="{{ path('app_booking_index_all', { page: page + 1 }) }}">Next</a>
  {% endif %}
  <a href="{{ path('app_booking_index_all', { page: lastPage }) }}">{{ lastPage }} (Last page)</a>
{% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}
{% block title %}
  New Booking
{% endblock %}

{% block body %}
  {% block header %}
    {{ parent() }}
  {% endblock %}
  <h1>Create new Booking</h1>
  {{ 'Price per night: ' }}<span id="price">{{ price }}</span>
  {{ 'Total price: ' }}<span id="total_price"></span>
  {{ include('booking/_form.html.twig') }}
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const startDateInput = document.getElementById('booking_start_date')
      const endDateInput = document.getElementById('booking_end_date')
      const totalPriceInput = document.getElementById('booking_total_price')
      const totalPriceSpan = document.getElementById('total_price')
      const pricePerNightSpan = document.getElementById('price')
    
      function calculatePrice() {
        const startDateValue = startDateInput.value
        const endDateValue = endDateInput.value
    
        if (startDateValue && endDateValue) {
          const diffMs = new Date(endDateValue) - new Date(startDateValue)
          const diffDays = diffMs / (1000 * 60 * 60 * 24)
          const pr = parseFloat(pricePerNightSpan.innerText)
          if (!isNaN(pr) && diffDays > 0) {
            const total = (pr * diffDays).toFixed(2)
            totalPriceInput.value = total
            totalPriceSpan.innerText = total
          } else {
            totalPriceInput.value = ''
            totalPriceSpan.innerText = '0'
          }
        }
      }
      startDateInput.addEventListener('change', calculatePrice)
      endDateInput.addEventListener('change', calculatePrice)
    
      if (startDateInput.value && endDateInput.value) {
        calculatePrice()
      }
    })
  </script>

  <a href="{{ path('app_booking_index') }}" class="btn btn-primary">back to list</a>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Booking
{% endblock %}

{% block body %}
  <h1>Booking</h1>

  <table class="table">
    <tbody>
      <tr>
        <th>Id</th>
        <td>{{ booking.id }}</td>
      </tr>
      <tr>
        <th>Start_date</th>
        <td>{{ booking.startDate ? booking.startDate|date('Y-m-d') : '' }}</td>
      </tr>
      <tr>
        <th>End_date</th>
        <td>{{ booking.endDate ? booking.endDate|date('Y-m-d') : '' }}</td>
      </tr>
      <tr>
        <th>Total_price</th>
        <td>{{ booking.totalPrice }}</td>
      </tr>
    </tbody>
  </table>

  <a href="{{ path('app_booking_index') }}" class="btn btn-primary">back to list</a>

  <a href="{{ path('app_booking_edit', { id: booking.id }) }}" class="btn btn-primary">edit</a>

  {{ include('booking/_delete_form.html.twig') }}
{% endblock %}